// Copyright 2025 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Mkprefix generates testdata/prefix.txt, a file of test vectors for
// [mpt.Tree.Scan], [mpt.ProvePrefix], and [mpt.VerifyPrefix].
//
// Usage:
//
//	go run testdata/mkprefix.go > testdata/prefix.txt
package main

//go:generate sh -c "go run mkprefix.go >prefix.txt"

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"os"
	"slices"

	"filippo.io/torchwood/mpt"
)

func main() {
	var g gen
	g.header()
	g.emptyTree()
	g.textTrees()
	g.hashTree()
	if _, err := os.Stdout.WriteString(g.String()); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// gen accumulates test output.
type gen struct {
	buf bytes.Buffer
}

func (g *gen) String() string { return g.buf.String() }

// Output methods.

func (g *gen) printf(format string, args ...any) {
	fmt.Fprintf(&g.buf, format, args...)
}

func (g *gen) comment(line string) {
	if line != "" {
		line = " " + line
	}
	g.printf("#%s\n", line)
}

func (g *gen) blank() { g.printf("\n") }

func (g *gen) section(title string) {
	g.printf("# === %s ===\n\n", title)
}

func (g *gen) kv(key, val []byte) {
	ks, vs := encHex(key), encHex(val)
	if len(key) == 0 {
		ks = "''"
	}
	if len(val) == 0 {
		vs = "''"
	}
	g.printf("kv %s %s\n", ks, vs)
}

func (g *gen) snap(h mpt.Hash) {
	g.printf("snap %s\n", encHex(h[:]))
}

func (g *gen) prefix(p []byte) {
	if len(p) == 0 {
		g.printf("prefix ''\n")
		return
	}
	g.printf("prefix %s\n", encHex(p))
}

func (g *gen) hash(h mpt.Hash) {
	g.printf("hash %s\n", encHex(h[:]))
}

// proof writes a formatted proof line.
// ok indicates whether the proof is a sequence of path steps only (true,
// the shape ProvePrefix returns when the prefix's subtree was found) or
// begins with a key-value pair (false, the shape ProvePrefix returns
// when no key in the tree has the prefix).
func (g *gen) proof(p mpt.Proof, ok bool) {
	if len(p) == 0 {
		g.printf("proof ''\n")
		return
	}
	groups := fmtGroups([]byte(p), ok)
	if len(groups) == 1 {
		g.printf("proof %s\n", groups[0])
		return
	}
	for i, gr := range groups {
		switch {
		case i == 0:
			g.printf("proof %s \\\n", gr)
		case i < len(groups)-1:
			g.printf("\t%s \\\n", gr)
		default:
			g.printf("\t%s\n", gr)
		}
	}
}

// encHex formats bytes as a hex string.
func encHex(b []byte) string {
	return hex.EncodeToString(b)
}

// fmtGroups splits raw proof bytes into display groups.
// Each group is a space-separated hex string that should appear on one line.
func fmtGroups(data []byte, ok bool) []string {
	var groups []string
	if !ok {
		// altkey: varint(len) key
		keyLen, n := binary.Uvarint(data)
		groups = append(groups, encHex(data[:n])+" "+encHex(data[n:n+int(keyLen)]))
		data = data[n+int(keyLen):]
		// altval: varint(len) val
		valLen, n := binary.Uvarint(data)
		groups = append(groups, encHex(data[:n])+" "+encHex(data[n:n+int(valLen)]))
		data = data[n+int(valLen):]
	}
	// path steps: varint(bit) + 32-byte hash
	for len(data) > 0 {
		_, n := binary.Uvarint(data)
		groups = append(groups, encHex(data[:n])+" "+encHex(data[n:n+32]))
		data = data[n+32:]
	}
	return groups
}

// Tree and probe helpers.

// emitTree builds an in-memory tree from kvs, emits its kv and snap lines
// (with the keys in sorted order, for readability), and returns the tree,
// its key-value pairs sorted by [mpt.KeyVal.CompareKey], and its snapshot.
func (g *gen) emitTree(kvs []mpt.KeyVal) (mpt.Tree, []mpt.KeyVal, mpt.Snapshot) {
	t := mpt.NewMemTree()
	for _, kv := range kvs {
		if err := t.Set(kv.Key, kv.Val); err != nil {
			panic(err)
		}
	}
	sorted := slices.Clone(kvs)
	slices.SortFunc(sorted, mpt.KeyVal.CompareKey)
	version := int64(1)
	if len(kvs) == 0 {
		version = 0
	}
	snap, err := t.Snap(version)
	if err != nil {
		panic(err)
	}
	for _, kv := range sorted {
		g.kv(kv.Key, kv.Val)
	}
	g.snap(snap.Hash)
	return t, sorted, snap
}

// probePrefix emits one prefix/hash/proof group testing prefix against t.
func (g *gen) probePrefix(t mpt.Tree, prefix []byte) {
	path, err := t.Path(prefix)
	if err != nil {
		panic(err)
	}
	hash, proof, err := mpt.ProvePrefix(prefix, path)
	if err != nil {
		panic(err)
	}
	g.prefix(prefix)
	g.hash(hash)
	g.proof(proof, hash != mpt.EmptyTreeHash())
	g.blank()
}

// Test generation methods.

func (g *gen) header() {
	g.comment("Test vectors for mpt.Tree.Scan, mpt.ProvePrefix, and mpt.VerifyPrefix,")
	g.comment("generated by mkprefix.go.")
	g.comment("")
	g.comment("Each test is a run of zero or more kv lines followed by a snap line,")
	g.comment("building and snapshotting a tree, followed by zero or more")
	g.comment("prefix/hash/proof groups tested against that snapshot. The kv set is")
	g.comment("cleared after each snap line, so any kv lines that follow belong to")
	g.comment("the next test. Blank lines and lines beginning with # are ignored.")
	g.comment("")
	g.comment("Format:")
	g.comment("  kv HEXKEY HEXVAL   - add a key-value pair to the current tree")
	g.comment("  snap HEXHASH       - snapshot the tree; its hash must equal HEXHASH")
	g.comment("  prefix HEXPREFIX   - set the prefix under test")
	g.comment("  prefix ''          - set the prefix to empty (zero-length)")
	g.comment("  hash HEXHASH       - ProvePrefix(prefix) hash should equal HEXHASH")
	g.comment("  proof HEXPROOF     - ProvePrefix(prefix) proof, verified with VerifyPrefix")
	g.comment("")
	g.comment("For each prefix/hash/proof group, a conformance test should also")
	g.comment("collect the pairs among the tree's own kv lines whose key has the")
	g.comment("prefix (using HasPrefix), and check that: Scan(prefix) yields exactly")
	g.comment("that set, in key order; TreeHash of that set equals the recorded")
	g.comment("hash; and VerifyPrefix(snap, prefix, hash, proof) succeeds.")
	g.comment("")
	g.comment("Proof lines may be continued with \\ at end of line;")
	g.comment("continuation lines conventionally start with a tab.")
	g.comment("The hex for kv, snap, prefix, hash, and proof may contain spaces.")
	g.comment("")
	g.comment("DO NOT EDIT. Generated by:")
	g.comment("  go run testdata/mkprefix.go > testdata/prefix.txt")
	g.blank()
}

// prefixKeys are keys chosen to exercise the key padding rules:
// some are prefixes of others, and some contain 0x00 and 0xFF bytes.
var prefixKeys = []string{
	"",
	"\x00",
	"\xff",
	"a",
	"a\x00",
	"a\xff",
	"ab",
	"ab\x00",
	"abc",
	"abd",
	"b",
	"ba",
	"bb",
	"c",
}

// prefixList returns the prefixes to try against a tree holding keys.
// It returns every byte prefix of every key, plus a few extensions
// that are not prefixes of any key.
func prefixList(keys []string) []string {
	seen := make(map[string]bool)
	var list []string
	add := func(p string) {
		if !seen[p] {
			seen[p] = true
			list = append(list, p)
		}
	}
	for _, k := range keys {
		for i := 0; i <= len(k); i++ {
			add(k[:i])
			for _, b := range []string{"\x00", "\xff", "z"} {
				add(k[:i] + b)
			}
		}
	}
	return list
}

// textVal returns a deterministic 32-byte value for index i,
// paired with the literal text keys in prefixKeys.
func textVal(i int) mpt.Val {
	s := sha256.Sum256([]byte(fmt.Sprintf("prefix-text-val-%d", i)))
	return s[:]
}

func (g *gen) emptyTree() {
	g.section("Empty tree")
	t, _, _ := g.emitTree(nil)
	for _, p := range prefixList(prefixKeys) {
		g.probePrefix(t, []byte(p))
	}
}

// textTrees builds a tree from each prefix of prefixKeys (0 keys, 1 key,
// ..., all of them), using the keys themselves (not hashes) so that the
// trees exercise shared prefixes and the key padding rules, and checks
// every prefix in prefixList(prefixKeys) against each one.
func (g *gen) textTrees() {
	for n := range len(prefixKeys) + 1 {
		g.section(fmt.Sprintf("Text keys, %d key(s)", n))
		var kvs []mpt.KeyVal
		for i, k := range prefixKeys[:n] {
			kvs = append(kvs, mpt.KeyVal{Key: mpt.Key(k), Val: textVal(i)})
		}
		t, _, _ := g.emitTree(kvs)
		for _, p := range prefixList(prefixKeys) {
			g.probePrefix(t, []byte(p))
		}
	}
}

// hashTree builds one tree of 200 SHA256-derived keys (as a real
// application would use) and checks prefixes of the 10 smallest keys,
// at every length up to 3 bytes, plus prefixes that match no key.
func (g *gen) hashTree() {
	g.section("Hash keys")
	const n = 200
	var kvs []mpt.KeyVal
	for i := range n {
		k := sha256.Sum256([]byte(fmt.Sprintf("prefix-key-%d", i)))
		v := sha256.Sum256([]byte(fmt.Sprintf("prefix-hash-val-%d", i)))
		kvs = append(kvs, mpt.KeyVal{Key: k[:], Val: v[:]})
	}
	t, sorted, _ := g.emitTree(kvs)

	var prefixes [][]byte
	for _, kv := range sorted[:10] {
		for i := range 4 {
			prefixes = append(prefixes, kv.Key[:i])
		}
	}
	for i := range 20 {
		s := sha256.Sum256([]byte(fmt.Sprintf("prefix-miss-%d", i)))
		prefixes = append(prefixes, s[:1+i%3])
	}
	for _, p := range prefixes {
		g.probePrefix(t, p)
	}
}
