// Copyright 2025 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Mktreehash generates testdata/treehash.txt, a file of test vectors for [mpt.TreeHash].
//
// Usage:
//
//	go run testdata/mktreehash.go > testdata/treehash.txt
package main

//go:generate sh -c "go run mktreehash.go >treehash.txt"

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"slices"

	"filippo.io/torchwood/mpt"
)

func main() {
	var g gen
	g.header()
	g.emptyTree()
	g.singleLeaf()
	g.twoLeaves()
	g.keyOrderingAndBitPositions()
	g.variableLengthKeys()
	g.paddingSensitiveOrdering()
	g.variableLengthValues()
	g.largeTrees()
	if _, err := os.Stdout.WriteString(g.String()); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// gen accumulates test output.
type gen struct {
	buf bytes.Buffer
}

func (g *gen) String() string { return g.buf.String() }

func (g *gen) printf(format string, args ...any) {
	fmt.Fprintf(&g.buf, format, args...)
}

func (g *gen) comment(line string) {
	if line != "" {
		line = " " + line
	}
	g.printf("#%s\n", line)
}

func (g *gen) blank() { g.printf("\n") }

func (g *gen) section(title string) {
	g.printf("# === %s ===\n\n", title)
}

func (g *gen) kv(key, val []byte) {
	ks, vs := hex.EncodeToString(key), hex.EncodeToString(val)
	if len(key) == 0 {
		ks = "''"
	}
	if len(val) == 0 {
		vs = "''"
	}
	g.printf("kv %s %s\n", ks, vs)
}

func (g *gen) hash(h mpt.Hash) {
	g.printf("hash %s\n", hex.EncodeToString(h[:]))
}

func bytesCompareKeyVal(a, b mpt.KeyVal) int {
	return bytes.Compare(a.Key, b.Key)
}

// computeHash sorts key-value pairs by key and computes the tree hash.
func computeHash(kvs []mpt.KeyVal) mpt.Hash {
	kvs = slices.Clone(kvs)
	slices.SortFunc(kvs, mpt.KeyVal.Compare)
	return mpt.TreeHash(slices.Values(kvs))
}

// emitSorted sorts kvs in bytes.Compare order, emits them, then emits the hash.
func (g *gen) emitSorted(kvs []mpt.KeyVal) {
	h := computeHash(kvs)
	slices.SortFunc(kvs, bytesCompareKeyVal)
	for _, kv := range kvs {
		g.kv(kv.Key, kv.Val)
	}
	g.hash(h)
}

// dkey returns sha256("key:<i>") as a byte slice.
func dkey(i int) []byte {
	h := sha256.Sum256([]byte(fmt.Sprintf("key:%d", i)))
	return h[:]
}

// dval returns sha256("val:<i>") as a byte slice.
func dval(i int) []byte {
	h := sha256.Sum256([]byte(fmt.Sprintf("val:%d", i)))
	return h[:]
}

func (g *gen) header() {
	g.comment("Test vectors for mpt.TreeHash, generated by mktreehash.go.")
	g.comment("")
	g.comment("Each test has a sequence of key-value pairs followed by a hash line.")
	g.comment("Blank lines and lines beginning with # are ignored.")
	g.comment("")
	g.comment("Format:")
	g.comment("  kv HEXKEY HEXVAL   - add a key-value pair to the current set")
	g.comment("  hash HEXHASH       - TreeHash of the current set should equal HEXHASH")
	g.comment("")
	g.comment("After each hash line, the set is cleared for the next test.")
	g.comment("")
	g.comment("DO NOT EDIT. Generated by:")
	g.comment("  go run testdata/mktreehash.go > testdata/treehash.txt")
	g.blank()
}

func (g *gen) emptyTree() {
	g.section("Empty tree")
	g.comment("No key-value pairs: hash is sha256 of empty string.")
	g.hash(computeHash(nil))
	g.blank()
}

func (g *gen) singleLeaf() {
	g.section("Single leaf")

	g.comment("One entry with typical 32-byte key and 32-byte value.")
	g.emitSorted([]mpt.KeyVal{
		{Key: dkey(0), Val: dval(0)},
	})
	g.blank()

	g.comment("One entry with 1-byte key and 1-byte value.")
	g.emitSorted([]mpt.KeyVal{
		{Key: []byte{0xAB}, Val: []byte{0xCD}},
	})
	g.blank()

	g.comment("One entry with empty key and empty value.")
	g.emitSorted([]mpt.KeyVal{
		{Key: []byte{}, Val: []byte{}},
	})
	g.blank()

	g.comment("One entry with long key (200 bytes) and long value (200 bytes).")
	longKey := make([]byte, 200)
	longVal := make([]byte, 200)
	for i := range longKey {
		longKey[i] = byte(i)
	}
	for i := range longVal {
		longVal[i] = byte(i + 100)
	}
	g.emitSorted([]mpt.KeyVal{
		{Key: longKey, Val: longVal},
	})
	g.blank()
}

func (g *gen) twoLeaves() {
	g.section("Two leaves")

	g.comment("Two 32-byte keys differing at bit 0 (0x00... vs 0x80...).")
	k1 := make([]byte, 32)
	k2 := make([]byte, 32)
	k2[0] = 0x80
	g.emitSorted([]mpt.KeyVal{
		{Key: k1, Val: dval(10)},
		{Key: k2, Val: dval(11)},
	})
	g.blank()

	g.comment("Two 32-byte keys differing at bit 7 (0x00... vs 0x01...).")
	k3 := make([]byte, 32)
	k4 := make([]byte, 32)
	k4[0] = 0x01
	g.emitSorted([]mpt.KeyVal{
		{Key: k3, Val: dval(12)},
		{Key: k4, Val: dval(13)},
	})
	g.blank()

	g.comment("Two 32-byte keys differing at bit 8 (0x0000... vs 0x0080...).")
	k5 := make([]byte, 32)
	k6 := make([]byte, 32)
	k6[1] = 0x80
	g.emitSorted([]mpt.KeyVal{
		{Key: k5, Val: dval(14)},
		{Key: k6, Val: dval(15)},
	})
	g.blank()

	g.comment("Two keys sharing a long common prefix, differing late.")
	k7 := make([]byte, 32)
	k8 := make([]byte, 32)
	for i := range 30 {
		k7[i] = 0xAA
		k8[i] = 0xAA
	}
	k7[30] = 0x00
	k8[30] = 0x01
	g.emitSorted([]mpt.KeyVal{
		{Key: k7, Val: dval(16)},
		{Key: k8, Val: dval(17)},
	})
	g.blank()
}

func (g *gen) keyOrderingAndBitPositions() {
	g.section("Key ordering and bit positions")

	g.comment("Three entries at 0x00, 0x40, 0x80 (unbalanced tree).")
	k1 := make([]byte, 32)
	k2 := make([]byte, 32)
	k2[0] = 0x40
	k3 := make([]byte, 32)
	k3[0] = 0x80
	g.emitSorted([]mpt.KeyVal{
		{Key: k1, Val: dval(20)},
		{Key: k2, Val: dval(21)},
		{Key: k3, Val: dval(22)},
	})
	g.blank()

	g.comment("Four entries forming a balanced tree.")
	b1 := make([]byte, 32)
	b2 := make([]byte, 32)
	b2[0] = 0x40
	b3 := make([]byte, 32)
	b3[0] = 0x80
	b4 := make([]byte, 32)
	b4[0] = 0xC0
	g.emitSorted([]mpt.KeyVal{
		{Key: b1, Val: dval(23)},
		{Key: b2, Val: dval(24)},
		{Key: b3, Val: dval(25)},
		{Key: b4, Val: dval(26)},
	})
	g.blank()

	g.comment("Keys differing at bit > 127 (multi-byte varint encoding).")
	hi1 := make([]byte, 32)
	hi2 := make([]byte, 32)
	for i := range 16 {
		hi1[i] = 0xFF
		hi2[i] = 0xFF
	}
	hi1[16] = 0x00
	hi2[16] = 0x80
	g.emitSorted([]mpt.KeyVal{
		{Key: hi1, Val: dval(27)},
		{Key: hi2, Val: dval(28)},
	})
	g.blank()
}

func (g *gen) variableLengthKeys() {
	g.section("Variable-length keys")

	g.comment("One key is a prefix of the other (0x12 and 0x1234).")
	g.emitSorted([]mpt.KeyVal{
		{Key: []byte{0x12}, Val: []byte{0xAA}},
		{Key: []byte{0x12, 0x34}, Val: []byte{0xBB}},
	})
	g.blank()

	g.comment("Two keys of different lengths, not prefixes of each other.")
	g.emitSorted([]mpt.KeyVal{
		{Key: []byte{0x12}, Val: []byte{0xCC}},
		{Key: []byte{0x34, 0x56}, Val: []byte{0xDD}},
	})
	g.blank()

	g.comment("Mix of 1-byte and 32-byte keys.")
	g.emitSorted([]mpt.KeyVal{
		{Key: []byte{0x10}, Val: []byte{0x01}},
		{Key: dkey(30), Val: dval(30)},
		{Key: []byte{0x90}, Val: []byte{0x02}},
	})
	g.blank()

	g.comment("Empty key (length 0) with a non-empty key.")
	g.emitSorted([]mpt.KeyVal{
		{Key: []byte{}, Val: []byte{0xEE}},
		{Key: []byte{0xFF}, Val: []byte{0x11}},
	})
	g.blank()
}

func (g *gen) paddingSensitiveOrdering() {
	g.section("Padding-sensitive ordering")

	g.comment("Keys whose ordering depends on the padding pattern 00 FF FF FF...")
	g.comment("K={AB} pads as AB 00 FF FF...")
	g.comment("K||00={AB,00} pads as AB 00 00 FF FF...")
	g.comment("K||00||FF={AB,00,FF} pads as AB 00 FF 00 FF FF...")
	g.comment("K||00||FE={AB,00,FE} pads as AB 00 FE 00 FF FF...")
	g.comment("K||01={AB,01} pads as AB 01 00 FF FF...")
	g.comment("Sorted order: K||00 < K||00||FE < K||00||FF < K < K||01")
	g.blank()

	K := []byte{0xAB}
	K00 := []byte{0xAB, 0x00}
	K00FF := []byte{0xAB, 0x00, 0xFF}
	K00FE := []byte{0xAB, 0x00, 0xFE}
	K01 := []byte{0xAB, 0x01}

	g.comment("All five keys together.")
	g.emitSorted([]mpt.KeyVal{
		{Key: K, Val: []byte{0x01}},
		{Key: K00, Val: []byte{0x02}},
		{Key: K00FF, Val: []byte{0x03}},
		{Key: K00FE, Val: []byte{0x04}},
		{Key: K01, Val: []byte{0x05}},
	})
	g.blank()

	g.comment("K vs K||00: prefix with padding 0x00 byte.")
	g.emitSorted([]mpt.KeyVal{
		{Key: K, Val: []byte{0x11}},
		{Key: K00, Val: []byte{0x12}},
	})
	g.blank()

	g.comment("K vs K||00||FF: K||00||FF matches padding through two bytes.")
	g.emitSorted([]mpt.KeyVal{
		{Key: K, Val: []byte{0x21}},
		{Key: K00FF, Val: []byte{0x22}},
	})
	g.blank()

	g.comment("K vs K||01: K||01 sorts after K.")
	g.emitSorted([]mpt.KeyVal{
		{Key: K, Val: []byte{0x31}},
		{Key: K01, Val: []byte{0x32}},
	})
	g.blank()

	g.comment("K||00||FE vs K||00||FF: differ in padding region.")
	g.emitSorted([]mpt.KeyVal{
		{Key: K00FE, Val: []byte{0x41}},
		{Key: K00FF, Val: []byte{0x42}},
	})
	g.blank()

	g.comment("K||00||FF vs K: K||00||FF < K because padding 0x00 at len(short) < padding 0xFF.")
	g.comment("This is the critical case: K||00||FF matches K's padding through")
	g.comment("two bytes (00, FF), then K||00||FF's own padding starts 0x00")
	g.comment("while K's continued padding is 0xFF.")
	g.emitSorted([]mpt.KeyVal{
		{Key: K00FF, Val: []byte{0x51}},
		{Key: K, Val: []byte{0x52}},
	})
	g.blank()

	g.comment("Empty key vs single 0x00 byte key.")
	g.comment("Empty pads as 00 FF FF..., {0x00} pads as 00 00 FF FF...")
	g.comment("{0x00} < empty because at byte 1: 0x00 < 0xFF.")
	g.emitSorted([]mpt.KeyVal{
		{Key: []byte{}, Val: []byte{0x61}},
		{Key: []byte{0x00}, Val: []byte{0x62}},
	})
	g.blank()

	g.comment("Key K||00||FF||FF: extends padding match further.")
	g.comment("K pads as AB 00 FF FF FF..., K||00||FF||FF pads as AB 00 FF FF 00 FF FF...")
	g.comment("They match through 3 padding bytes, then diverge at byte 4.")
	K00FFFF := []byte{0xAB, 0x00, 0xFF, 0xFF}
	g.emitSorted([]mpt.KeyVal{
		{Key: K00FFFF, Val: []byte{0x71}},
		{Key: K, Val: []byte{0x72}},
	})
	g.blank()

	g.comment("Three levels of prefix nesting: K, K||00, K||00||00.")
	g.comment("K||00||00 < K||00 < K.")
	K0000 := []byte{0xAB, 0x00, 0x00}
	g.emitSorted([]mpt.KeyVal{
		{Key: K, Val: []byte{0x81}},
		{Key: K00, Val: []byte{0x82}},
		{Key: K0000, Val: []byte{0x83}},
	})
	g.blank()

	g.comment("Key K of length 1023 and K||0x00 (length 1024).")
	g.comment("First differing bit is index 1024 * 8 (the 1025th byte), beyond MaxKeyLen (1024).")
	K1023 := bytes.Repeat([]byte{0xAB}, 1023)
	K1024a := append(bytes.Clone(K1023), 0x00)
	g.emitSorted([]mpt.KeyVal{
		{Key: K1023, Val: []byte{0x91}},
		{Key: K1024a, Val: []byte{0x92}},
	})
	g.blank()

	g.comment("Key K of length 1022 and K||0x00||0xFF (length 1024).")
	g.comment("First differing bit is index 1024 * 8 (the 1025th byte), beyond MaxKeyLen (1024).")
	K1022 := bytes.Repeat([]byte{0xAB}, 1022)
	K1024b := append(bytes.Clone(K1022), 0x00, 0xFF)
	g.emitSorted([]mpt.KeyVal{
		{Key: K1022, Val: []byte{0xA1}},
		{Key: K1024b, Val: []byte{0xA2}},
	})
	g.blank()
}

func (g *gen) variableLengthValues() {
	g.section("Variable-length values")

	g.comment("Same key set, different value lengths: values affect hash.")
	k1 := dkey(40)
	k2 := dkey(41)
	g.emitSorted([]mpt.KeyVal{
		{Key: k1, Val: []byte{0x01}},
		{Key: k2, Val: []byte{0x02}},
	})
	g.blank()

	g.comment("Same keys, longer values.")
	g.emitSorted([]mpt.KeyVal{
		{Key: k1, Val: []byte{0x01, 0x02, 0x03, 0x04, 0x05}},
		{Key: k2, Val: []byte{0x06, 0x07, 0x08, 0x09, 0x0A}},
	})
	g.blank()

	g.comment("Empty value vs non-empty value.")
	g.emitSorted([]mpt.KeyVal{
		{Key: dkey(42), Val: []byte{}},
		{Key: dkey(43), Val: []byte{0xFF, 0xFE}},
	})
	g.blank()
}

func (g *gen) largeTrees() {
	g.section("Large trees")

	g.comment("10 entries with deterministic keys.")
	var kvs10 []mpt.KeyVal
	for i := range 10 {
		kvs10 = append(kvs10, mpt.KeyVal{Key: dkey(i), Val: dval(i)})
	}
	g.emitSorted(kvs10)
	g.blank()

	g.comment("100 entries with deterministic keys.")
	var kvs100 []mpt.KeyVal
	for i := range 100 {
		kvs100 = append(kvs100, mpt.KeyVal{Key: dkey(i), Val: dval(i)})
	}
	g.emitSorted(kvs100)
	g.blank()
}
